language: ruby
rvm:
- ruby-head
- 2.4.1
- 2.3.4
- 2.2.7
addons:
  apt:
    packages:
    - libimlib2-dev
before_install:
- ruby ./extconf.rb
install:
- make
- make install
script:
- ruby -rimlib2 -e 'exit Imlib2::VERSION == "0.5.2"'
